In [9]:
import pandas as pd
import numpy as np

from scipy import stats

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score

In [10]:
df = pd.read_csv("../data/titanic_cleaned.csv")

df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Unknown,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Unknown,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Unknown,Southampton,no,True

In [11]:
df.describe()

         survived      pclass         age       sibsp       parch        fare
count  784.000000  784.000000  784.000000  784.000000  784.000000  784.000000
mean     0.411990    2.243622   29.650408    0.522959    0.415816   34.711740
std      0.492507    0.855056   13.734925    0.986231    0.836922   52.160151
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    1.000000   22.000000    0.000000    0.000000    8.050000
50%      0.000000    3.000000   28.250000    0.000000    0.000000   15.900000
75%      1.000000    3.000000   36.000000    1.000000    1.000000   34.109350
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [12]:
print("Mean Age:", df["age"].mean())

print("Median Age:", df["age"].median())

print("Mode Age:", df["age"].mode()[0])

print("Standard Deviation:", df["age"].std())

print("Skewness:", df["age"].skew())

Mean Age: 29.650408163265304
Median Age: 28.25
Mode Age: 28.25
Standard Deviation: 13.734925365696805
Skewness: 0.44177912604697694

In [13]:
male = df[df["sex"]=="male"]["fare"]

female = df[df["sex"]=="female"]["fare"]

t,p = stats.ttest_ind(male,female)

print("T-Test")

print("t =",t)

print("p =",p)

T-Test
t = -4.808619159050641
p = 1.823068331550657e-06

In [14]:
table = pd.crosstab(df["sex"],df["survived"])

chi2,p,dof,expected = stats.chi2_contingency(table)

print("Chi Square =",chi2)

print("p value =",p)

Chi Square = 206.3995178801755
p value = 8.383408590582411e-47

In [15]:
X = df[["age","fare"]]

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

kmeans = KMeans(n_clusters=4, random_state=42)

df["Cluster"] = kmeans.fit_predict(X_scaled)

df[["age","fare","Cluster"]].head()

    age     fare  Cluster
0  22.0   7.2500        2
1  38.0  71.2833        0
2  26.0   7.9250        2
3  35.0  53.1000        0
4  35.0   8.0500        2

In [16]:
X = df[["age","fare","pclass"]]

y = df["survived"]

X_train,X_test,y_train,y_test = train_test_split(
    X,y,test_size=0.2,random_state=42
)

model = LogisticRegression(max_iter=1000)

model.fit(X_train,y_train)

pred = model.predict(X_test)

print("Accuracy =",accuracy_score(y_test,pred))

Accuracy = 0.643312101910828

# Task 4 Conclusion

- Calculated descriptive statistics.
- Performed T-Test.
- Performed Chi-Square Test.
- Created 4 customer clusters using K-Means.
- Built Logistic Regression model for survival prediction.